name: Output Example Workflow

on:
  workflow_dispatch:
  
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.job1_output.outputs.JOB1_OUTPUT }}
    steps:
      - id: job1_output
        run: |
          echo "JOB1_OUTPUT=job1_output" >> "$GITHUB_OUTPUT"
      - run: |
          echo ${{ steps.job1_output.outputs.JOB1_OUTPUT }}
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: |
          echo ${{ needs.job1.outputs.output1 }}
